export interface clients {
KUNDENID :number 
BEZEICHNUNG :string 
KUNDESEIT : Date
VERTRAGSPARTEI_CD :string 
LOESCH_CD :string 
LOESCHDATUM : Date
CRTDATUM : Date
CRTUSER :string 
MUTDATUM : Date
MUTUSER :string 
PSEUDOACCOUNT_CD :string 
KUNDEBESUCH : Date
BEZEICHNUNGVERTRAG :string 
PSEUDONYM :string 
RECHTSDOMIZIL_CD :string 
KORRESPONDENZSPRACH_CD :string 
MIT_PROFIL_CD :string 
GEMEINSCHAFTSKONTO_CD :string 
PIN :string 
VERWENDUNGSZWECK :string 
IDENTIFIKATIONSART_CD :string 
VERMOEGENSURSPRUNG_CD :string 
VERMOEGENSURSPRUNG :string 
GELDVONKONTO :string 
BISHERIGEBETREUUNG :string 
BISHERIGEBETREUUNGSEIT : Date
MANUALOPEN_CD :string 
EIN_VERMOEGEN_CD :string 
REGIONZAHLUNG_CD :string 
EIN_VERMOEGENART_CD :string 
SPEZ_WUENSCHE_CD :string 
MANAGER_CD :string 
RISKINDEX :number 
RISKINDEX_GUELTISEIT : Date
RISKINDEX_LETZTEBERECHNUNG : Date
KONTOEROEFFNUNGSART_CD :string 
RISKINDEXBERECHNEN_CD :string 
KUNDENNATUR_CD :string 
RISIKOKATEGORIE_CD :string 
PEP_CD :string 
SPEZIALKATEGORIE_CD :string 
NATURE_CD :string 
NAME :string 
LEDIGERNAME :string 
VORNAME :string 
CDPARTC :string 
NATIONALITAET_CD :string 
RISIKOLAND_CD :string 
PERSOENLICHBEKANNT_CD :string 
RISIKOTAETIGKEIT_CD :string 
STEUERDOMIZIL_CD :string 
EU_TAXSTATUS_CD :string 
TIN :string 
APSYS_CDROLPERSI :string 
VERTRAGSPRACH_CD :string 
VERMOEGENSKATEGORIE_IHAG_CD :string 
APSYS_INTISHS :string 
APSYS_INTILGS :string 
GESAMTVERMOEGEN_CD : number 
COMPLIANCE_OK_CD :string 
COMPLIANCE_OK_BEMERKUNG :string 
COMPLIANCE_OK_DATUM : Date
COMPLIANCE_OK_USERID :string 
EIN_VERMOEGEN : number 
SEGMENTIERUNG_CD : number 
AKTID : number 
VALIDID : number 
VALID_CD :string 
VALIDUSER :string 
ENC_SALT :string 
BEZEICHNUNG_ENC :string 
APSYS_CDMOTIFPARTS :string 
APSYS_CDINDUS0S :string 
APSYS_FLAGPREAVISEXEC :string 
APSYS_CDAVIOBISPECC :string 
APSYS_FLAGHISPERC :string 
APSYS_REPAMANUC :string 
APSYS_PERDEVCALC :string 
APSYS_FLAGUKTAXC :string 
APSYS_CDNOGAS :string 
APSYS_STATFISCC :string 
APSYS_FLAGFWTI :string 
APSYS_FLAGFWTUKNRSDI :string 
APSYS_FLAGFWTTAXSPEGEI :string 
APSYS_CDFWTOPTREGULFISCANCC :string 
APSYS_CDFWTSTATREGULFISCANCC :string 
APSYS_CDFWTOPTREGULFISCFUTC :string 
STEUERLAND_ABGST_CD :string 
APSYS_CDNATURES :string 
APSYS_SHNAS :string 
APSYS_CDPYHQDOMIS :string 
APSYS_CDPERMI :number 
APSYS_IDRCIS :string 
APSYS_FLAGISTTC :string 
APSYS_DEVEVALS :string 
APSYS_IDSTRUCS :string 
APSYS_SUIVIAGTS :string 
APSYS_CDINDUSCSSFS :string 
APSYS_CDINDUSBLUXS :string 
APSYS_CDINDUSSBUBA :string 
APSYS_CDINDUSSBNS :string 
APSYS_GRMTEVALS :string 
APSYS_IDPOCS :string 
APSYS_INFO :string 
APSYS_IDENTS :string 
APSYS_STATUS_OPEC :string 
APSYS_ERRI :number 
NATIONALITAET2_CD :string 
NATIONALITAET3_CD :string 
VERMOEGENSURSPRUNG2_CD :string 
VERMOEGENSURSPRUNG2 :string 
APPROVAL_STEP1_CD :string 
APPROVAL_STEP1_USER :string 
APPROVAL_STEP1_DATE : Date
APPROVAL_STEP2_CD :string 
APPROVAL_STEP2_USER :string 
APPROVAL_STEP2_DATE : Date
APPROVAL_STEP3_CD :string 
APPROVAL_STEP3_USER :string 
APPROVAL_STEP3_DATE : Date
APPROVAL_STEP4_CD :string 
APPROVAL_STEP4_USER :string 
APPROVAL_STEP4_DATE : Date
APPROVAL_STEP5_CD :string 
APPROVAL_STEP5_USER :string 
APPROVAL_STEP5_DATE : Date
APPROVAL_STEP1_BEM :string 
APPROVAL_STEP2_BEM :string 
APPROVAL_STEP3_BEM :string 
APPROVAL_STEP4_BEM :string 
APPROVAL_STEP5_BEM :string 
APPROVAL_STEP1_ASSES_CD :number 
APPROVAL_STEP2_ASSES_CD :number 
APPROVAL_STEP3_ASSES_CD :number 
APPROVAL_STEP4_ASSES_CD :number 
APPROVAL_STEP5_ASSES_CD :number 
APPROVAL_STATUS_CD :number 
CLIENT_STATUS_CD :string 
DISCHARGE_ORDERS_CD :string 
PRINT_SUMMARY_HOLDMAIL_ONLY_CD :string 
EBANKING_CONTRACT_CD :string 
EBANKING_CONTRACT_LANGUAGE_CD :string 
APSYS_DTECHDIARYL : Date
APSYS_MOTDIARYS :string 
APSYS_IDTYPCLIIRSS :string 
APSYS_IDRCIQIS :string 
APSYS_IDRCIFATCAS :string 
MAILING_TARIF_TYPE_CD :number 
REGISTERED_CD :string 
REGISTERED_MAIL_CD :string 
APSYS_NBPERSCPARTIEL :number 
ASSET_VALUE_TIER_CD :string 
RELATIONSHIP_TYPE_AML_CD :string 
CB_ASSET_VALUE_TIER_CD :string 
APPROVAL_SCORE :number 
APPROVAL_SCORE_STEPS :number 
APSYS_DTDEBPARTL : Date
APSYS_DTFINPARTL : Date
APSYS_CDMOTIFCLOS :string 
APSYS_CDNATURECPARTIEEMIRC :string 
APSYS_FLAGOTHEREMIRC :string 
APSYS_CDINDUSEMIRS :string 
OPENED_IN_APSYS_DATE : Date
APSYS_CDNATURECPARTIEFMIAC :string 
EBANKING_CLOSED_CD :string 
EBANKING_CLOSINGDATE : Date
KYC_REVIEW_PROCESS_START_DATE : Date
REMARKS :string
TRANSACTION_BL_COUNTRY_CD :number 
CLIENTGROUP_CD :number 
RISKINDEX_CALC :number 
LAST_CALC_CRI_MUTDATUM : Date
RISIKOKATEGORIE_CALC_CD :string 
RISKINDEX_GROUP :number 
EST_AMOUNT_REM_WITH_MUTDATUM : Date
GESAMTVERMOEGEN_MUTDATUM : Date
TRANSACT_BL_COUNTRY_MUTDATUM : Date
ACCOUNTPURPOSE_MUTDATUM : Date
APSYS_FLAGDELDATAPERSI :string 
APSYS_DTWAITDELDATAPERSL : Date
NAME_ENC :string 
IN_APSYS_TEMP_ENTSPERREN_CD :string 
IN_APSYS_TEMP_ENTSP_USERID :string 
IN_APSYS_TEMP_ENTSP_DATUM : Date
APSYS_CDREGS :string 
RETENTION_ON_HOLD :string 
RETENTION_ON_HOLD_DATE : Date
RETENTION_ON_HOLD_REASON :string 
LOGICAL_ERASURE :string 
LOGICAL_ERASURE_DATE : Date
LOGICAL_ERASURE_REASON :string 
COMPLIANCE_MIN_RISK_CATEGORY :string 
COMPLIANCE_MIN_RISK_COMMENT :string 
CLIENT_STRUCTURE_CD :string 
CLIENT_SUBSTRUCTURE_CD :string 
}
